# Generated by Django 4.2.23 on 2025-08-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='main_news',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
